INSERT INTO dbo.tbl_cards
(name, hp, info, attack, damage, weak, resist, retreat, cardNumberInCollection, collectionId, typeId, stageId)
VALUES
(N'Squirtle', 40, N'Common', N'Bubble', N'10', N'Grass ×2', N'', 1, N'63/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Water'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Blastoise', 100, N'Holo Rare', N'Hydro Pump', N'40', N'Lightning ×2', N'', 3, N'2/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Water'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 2')),
(N'Charmander', 50, N'Common', N'Ember', N'30', N'Water ×2', N'', 1, N'46/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Fire'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Ivysaur', 60, N'Uncommon', N'Vine Whip', N'30', N'Fire ×2', N'', 2, N'30/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Grass'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 1')),
(N'Wartortle', 70, N'Uncommon', N'Withdraw; Bite', N'40', N'Grass ×2', N'', 1, N'42/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Water'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 1')),
(N'Lapras', 80, N'Rare', N'Water Gun', N'10+', N'Lightning ×2', N'', 2, N'10/62',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Fossil'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Water'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Articuno', 70, N'Holo Rare', N'Freeze Dry', N'30', N'Metal ×2', N'', 2, N'2/62',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Fossil'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Water'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Zapdos', 80, N'Holo Rare', N'Thunder', N'60', N'Fighting ×2', N'', 3, N'16/62',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Fossil'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Lightning'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Moltres', 70, N'Holo Rare', N'Wildfire', N'', N'Water ×2', N'', 2, N'12/62',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Fossil'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Fire'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Flareon', 70, N'Rare', N'Flamethrower', N'60', N'Water ×2', N'', 1, N'3/64',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Jungle'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Fire'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 1')),
(N'Vaporeon', 80, N'Rare', N'Water Gun', N'10+', N'Lightning ×2', N'', 2, N'12/64',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Jungle'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Water'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 1')),
(N'Jolteon', 70, N'Rare', N'Pin Missile', N'20×', N'Fighting ×2', N'', 1, N'20/64',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Jungle'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Lightning'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 1')),
(N'Scyther', 70, N'Holo Rare', N'Slash', N'30', N'Fire ×2', N'Fighting −30', 1, N'10/64',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Jungle'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Grass'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Snorlax', 90, N'Rare', N'Body Slam', N'30', N'Fighting ×2', N'', 4, N'11/64',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Jungle'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Colorless'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Dragonite', 100, N'Holo Rare', N'Slam', N'40×', N'Colorless ×2', N'Fighting −30', 1, N'4/62',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Fossil'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Dragon'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 2')),
(N'Haunter', 60, N'Uncommon', N'Nightmare', N'10', N'Darkness ×2', N'Fighting −30', 1, N'6/62',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Fossil'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Psychic'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 1')),
(N'Machop', 50, N'Common', N'Low Kick', N'20', N'Psychic ×2', N'', 1, N'52/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Fighting'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic')),
(N'Machoke', 80, N'Uncommon', N'Karate Chop', N'50', N'Psychic ×2', N'', 3, N'35/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Fighting'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 1')),
(N'Magneton', 80, N'Holo Rare', N'Selfdestruct', N'80', N'Fighting ×2', N'', 2, N'9/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Lightning'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Stage 1')),
(N'Mewtwo', 60, N'Rare', N'Psychic', N'10+', N'Psychic ×2', N'', 2, N'10/102',
 (SELECT collectionId FROM dbo.tbl_collections WHERE collectionsSetName = N'Base Set'),
 (SELECT typeId FROM dbo.tbl_types WHERE typeName = N'Psychic'),
 (SELECT stageId FROM dbo.tbl_stages WHERE stageName = N'Basic'));